name: CI tests
on:
  push:
  pull_request:
  workflow_dispatch: {}
jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node: [20, 22]
        os: [ubuntu-latest]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Contracts tests
        run: |
          pushd contracts
          npm ci
          npm test
          popd
      - name: Settlement tests
        run: |
          pushd settlement
          npm ci
          npm test
          popd
        env:
          CI: true
